### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by balthazar** [Apercu/Hestia#2]
Since we now have funds unlocked from our two "collaborators" we have, maybe it's time to set it on the store.

Would you mind doing it? I'm not experienced in this field.

**Comment by Kerumen** [comment]
Funds? I didn't see anything in my bank account 😕

**Comment by balthazar** [comment]
Oh nonono don't worry! It will appear soon!

**Comment by Kerumen** [comment]
I hope 💰 💵

**Comment by balthazar** [comment]
Oh but it might be a misunderstanding here: the funds are in bitcoins, not
dollars!

**Comment by balthazar** [comment]
[We have been cucked](https://itunes.apple.com/us/app/hestia/id950406538). I'm gonna close this. Forget the money, all of our sponsors are gone.. :sob:

**Comment by Kerumen** [comment]
OMG I can't believe it...

Le mer. 15 juin 2016 19:13, Balthazar Gronon notifications@github.com a
écrit :
